In [5]:
a = 1 + 1
print("answer",a)

answer 2


1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [9]:
import numpy as np
l = [12.23, 13.32, 100, 36.32]
a = np.array(l)
print('one dimentional', a)


one dimentional [ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>
<class 'list'>


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [2]:
import numpy as np
matrix = np.arange(2, 11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [3]:
import numpy as np
null_vector = np.zeros(10)
null_vector[6] = 11
print(null_vector)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [4]:
import numpy as np
array = np.arange(12, 38)
reversed_arr = array[::-1]
print(reversed_arr)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

In [15]:
import numpy as np
arr = np.ones((5, 8))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [20]:
import numpy as np
arr = np.ones((3, 3))
arr1 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [39]:
import numpy as np
arr = np.zeros((8,8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]    

In [41]:
import numpy as np
lst = [1, 2, 3, 4]
print(np.asarray(lst))
tup = ([6, 8, 9], [1, 8, 9])
print(np.asarray(tup))


[1 2 3 4]
[[6 8 9]
 [1 8 9]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

In [44]:
import numpy as np
arr = [10, 20, 30]
print(np.append(arr, [[40, 50, 60], [70, 80, 90]]))

[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [48]:
import numpy as np
original_array = np.array([1.0+0j, 0.70710678+0.70710678j])

real_part = np.real(original_array)

imaginary_part = np.imag(original_array)

print("Original array:", original_array)
print("Real part of the array:", real_part)
print("Imaginary part of the array:", imaginary_part)

Original array: [1.        +0.j         0.70710678+0.70710678j]
Real part of the array: [1.         0.70710678]
Imaginary part of the array: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [49]:
import numpy as np
arr = np.array([1,2,3], dtype=np.float64)
print("size", arr.size)
print("length", arr.itemsize)
print("byte", arr.nbytes)

size 3
length 8
byte 24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [50]:
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = [10, 30, 40]
print(np.intersect1d(arr1, arr2))

[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [53]:
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = [10, 30, 40, 50, 70, 90]
print(np.setdiff1d(arr1, arr2))

[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [57]:
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = [10, 30, 40, 50, 70]
print(np.setxor1d(arr1, arr2))

[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [58]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([4, 5])
print(np.greater(arr1, arr2))
print(np.greater_equal(arr1, arr2))
print(np.less(arr1, arr2))
print(np.less_equal(arr1, arr2))

[False False]
[False False]
[ True  True]
[ True  True]


15. Write a Python program to save a NumPy array to a text file.

In [63]:
import numpy as np
import os
arr = np.arange(12).reshape(4,3)
header = 'col1 col2 col3'
np.savetxt('temp.txt', arr, fmt="%d", header=header)
file = np.loadtxt('temp.txt')
print(file)
print(type(file))

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<class 'numpy.ndarray'>


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [64]:
import numpy as np
arr = np.array([[10, 20, 30], [20, 40, 50]])
flatten_arr = np.ravel(arr)
print(flatten_arr)

[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [65]:
import numpy as np
arr = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
type_arr = arr.astype(float)
print(type_arr)

[[ 2.  4.  6.]
 [ 6.  8. 10.]]


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [66]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]]

In [83]:
import numpy as np
lower_triangular_array = np.triu(np.ones((4, 4)))
print(lower_triangular_array)

[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]])
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [75]:
import numpy as np
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
concatenated_arr = np.concatenate((arr1, arr2), 1)
print(concatenated_arr)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [76]:
import numpy as np
x = np.array([0, 1, 2, 3, 4])
x.flags.writeable = False
try:
    x[0] = 1
except ValueError as e:
    print("Test the array is read-only or not:")
    print("Try to change the value of the first element:")
    print(f"Traceback (most recent call last):\n  File \"your_file_name.py\", line 6, in\n    x[0] = 1\nValueError: assignment destination is read-only")


Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
  File "your_file_name.py", line 6, in
    x[0] = 1
ValueError: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [95]:
import numpy as np
x= np.arange(16).reshape(4, 4)
for a in np.nditer(x, op_flags=['readwrite']):
    a[...] = 3 * a
print("New array elements:")
print(x)

New array elements:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]
 [36 39 42 45]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [80]:
import numpy as np
arr = np.arange(6).reshape(3, 2)
print(arr.tolist())

[[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [ ]:
import numpy as np
arr =np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
  0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
print("Print array values with precision 3:")
np.set_printoptions(precision=3)
print(arr)

25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with p

In [ ]:
import numpy as np
original_array = np.array([1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print("Original array elements:")
print(original_array)
np.set_printoptions(suppress=True)

print("\nPrint array values without scientific notation:")
print(original_array)

26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [ ]:
import numpy as np
arr1 = np.array([[10,20,30], [40,50,60]])
arr2 = np.array([[100], [200]])
print(np.append(arr1, arr2, axis=1))

Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [82]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
index = [0, 3, 4]

print("Delete first, fourth and fifth elements:")
new_x = np.delete(arr, index)
print(new_x)

Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
